### ISSUE TITLE
MacOS Rendering Bug

### ISSUE THREAD

**Issue by Platin21** [BennyQBD/CGFX5#4]
That's the result: 
<img width="797" alt="drawing" src="https://user-images.githubusercontent.com/20503931/39233801-bec19654-4871-11e8-8eda-2cef4d747cbf.png">
Which is probably not that what it should draw. (Note gl is pretty much dead on OSX/iOS)
It's the same output for debug and release build.

Used Xcode to build via CMake:
`./Unix-Build.sh Release -G "Xcode"`

**Comment by namark** [comment]
I've got something similar going on on Ubuntu 16.04, except I can also barely see some diagonal lines(or more like intermittent rows of pixels) going from the center of the window towards the top-right corner.

**Comment by BennyQBD** [comment]
How bizarre. To anyone with this issue, do you have the latest graphics drivers? What hardware is this running on, in particular what GPU?

In the latest commit, I've added a variable in main.cpp called "debuggerTemp". Anyone with this issue, please try running that with all possible values (0 through 3) and tell me what you see in each case.

**Comment by WebFreak001** [comment]
same issue on my archlinux machine with mesa
```
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.15-1-ARCH, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

This is what I see normally: https://wfr.moe/fHy9ow.mp4
This is what it looks like with 1 and 2: https://wfr.moe/fHjy5a.png
and with 3 it's completely blue

**Comment by namark** [comment]
I can't check now, but can confirm that I see exactly what is in the first link WebFreak001 posted, and my drivers are just a bit behind his.

**Comment by Platin21** [comment]
<img width="428" alt="config" src="https://user-images.githubusercontent.com/20503931/39262768-9dcc99d6-48c0-11e8-9140-2a9c4c171f6f.png">
It's german but you can see the gpu family. 
Running on MacOS High Sierra. (Latest GL Driver provided by apple)

Result setting 0: 
![setting0](https://user-images.githubusercontent.com/20503931/39263682-34c95138-48c3-11e8-9876-e2170e324810.gif)
Result seting 1:
![setting1](https://user-images.githubusercontent.com/20503931/39263697-39fc6f64-48c3-11e8-8fe9-c7dc921f4733.gif)
Result setting 2:
![setting2](https://user-images.githubusercontent.com/20503931/39263707-410210ca-48c3-11e8-86cf-0fe79759aa31.gif)
Result setting 3:
![setting3](https://user-images.githubusercontent.com/20503931/39263715-479f0ac8-48c3-11e8-898d-c4e37c9ca493.gif)

**Comment by DamianReloaded** [comment]
I can confirm I'm getting the same results than Platin21 above^ running Debian9 on both Intel and AMD Radeon 270x pitcairn GPUs. For reference the projects https://github.com/joshb/glsl_lighting , https://github.com/opengl-tutorials/ogl compile and run as expected. Maybe your video cards is too new Benny?

**Comment by janwaltl** [comment]
I literally ran into this issue in my project this weekend and spend good 2-3 hours just to locate it.
As it turns out some GPUs(looking at you Intel) do not count index buffer part of VAO state as they should. The results are those flickering lines. It looks to me like a driver bug and probably worth reporting. That said, fix is really easy, just call glBindBuffer explicitly before glBindVertexArray:
`glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,IBO);
glBindVertexArray(VAO);`

My Nvidia 1050TI works fine, Intel 630 integrated GPU works after this fix.
EDIT: These are my results https://imgur.com/a/YoBUeTL

**Comment by Thundzz** [comment]
_EDIT : posted almost at the same time as @JanWaltl, I think he might just  have figured out the answer._

I also managed to reproduce this bug on one of my laptops running Windows 10 and compiling with Visual Studio 2017. (GPU is Intel(R) HD Graphics 530, driver version 4.5.0, support until OpenGL 4.5)

I think I might have narrowed the search space for this bug a bit, but I still didn't quite solve the problem.

I am suspecting that there is some problem in the way the transform matrix is sent to the GPU. 

Here are the steps I followed and the results I obtained:

- I used `int32 debuggerTemp = 3`
- I went ahead and disabled the rotation and translation of the triangle in the code responsible for the updating of the scene. (still nothing displayed after this step)
- I implemented a print matrix function in Matrix.hpp:
```c++
	void print()
	{
		for (int i = 0; i < 4; i++) {
			for (int j = 0; j < 4; j++) {
				std::cout << m[i][j] << "\t";
			}
			std::cout << std::endl;
		}
	}
```
- I used this new method to print the `perspective * transform.toMatrix()` in `main.cpp`. Since there is no transform applied, the value of this matrix is constant, and is equal to:

![gif](https://user-images.githubusercontent.com/6213717/39274778-5ffd96e6-48e3-11e8-8f28-6d7f5db56a1d.gif)

- I forced this value for the matrix in the vertex shader:
```glsl
void main()
{
    mat4 transform = mat4(
        1.42815, 0      , 0     , 0,
        0       , 1.9042, 1     , 0,
        0       , 0     , 1     , 0,
        0       , 0     , 1     , 1
    );
    gl_Position = vec4(position, 1.0) * transform;
    //gl_Position = vec4(position, 1.0) * transformMat;
    texCoord0 = texCoord; 
}
``` 

- The triangle finally appears!
- **This can only happen if the `transformMat` variable in the vertex shader does not have the correct value!**

If you guys can try with the forced transform matrix to confirm we are all facing the same issue, that would be nice!

I might continue digging a bit, but I figured it might already help a bit if I shared this.

**Comment by BennyQBD** [comment]
Implemented the trick suggested by JanWaltl. Please let me know if this fixes it for anyone. Thanks for all the help debugging this everyone, it's all very helpful and much appreciated. Even if this latest fix doesn't work, I'm optimistic that the issue is being narrowed down effectively and will be resolved soon.

**Comment by DamianReloaded** [comment]
I'm sorry. It still shows the same behavior. Maybe you can give us a barebones main.cpp that would do what this project does so we can play with it more easily and any change we make would be more evident? This is, a single source that we would compile ala ""g++ main.cpp -lX11 -lEtceteralibs""

**Comment by janwaltl** [comment]
Sorry, that it didn't work. I found another thing, in createVertexArray() you enable attribute locations 0,1,2... But you don't specify which attributes in basicShader.glsl should be bound to which numbers. So driver can assign `transformMat` to lets say a location 7(which does not have any buffer attached). It works exactly like uniform locations. Solution is to query the shader for their location via glGetAttribLocation. But looking at your code, you want to have VAO independent of shaders and rely on that you pass them into createVertexArray in the same order as you defined them in shaders, which is reasonable. That can be achieved by layout qualifiers https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL) . It either requires #version 330 or GL_ARB_explicit_attrib_location extension.

I managed to get the code working by altering basicShader.glsl to:
[basicShader.txt](https://github.com/BennyQBD/CGFX5/files/1950732/basicShader.txt)
(Github refused to upload .glsl extension)

It also somehow removed the need to bind the index buffer as I suggested, sorry about that again, it's still needed for my application, so maybe I have another similiar bug that triggers it. 


EDIT: Just to clarify: Layout qualifier for attributes is really OpenGL 3.3+ (Uniform layout is OpenGL 4.3+) (see specs https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.3.30.pdf ). On older hardware it could be made available by  GL_ARB_explicit_attrib_location extension.  But you made a (reasonable) choice to use 3.3+ by using instanced arrays for matrices anyway.

**Comment by Mattbazooka** [comment]
I can confirm the fix from JanWaltl using:
```GLSL
layout(location=0) attribute vec3 position;
layout(location=1) attribute vec2 texCoord;
layout(location=2) attribute mat4 transformMat;
```
Although using `glGetAttribLocation` may be a better solution since the layout qualifier is only in OpenGL 4.3+.

**Comment by Thundzz** [comment]
I can confirm binding the attributes in the vertex shader to specific attribute locations fixes the problem on my Intel GPU! 
I think the previous hack can safely be reverted.

**Comment by DamianReloaded** [comment]
Confirmed ^ It works like a charm now on my radeon! Kudos JanWaltl !

**Comment by ghost** [comment]
Can confirm that JanWaltl's fix worked on debian 9 with amd open source driver

A smaller thing i noticed is that the res folder does not get copied over on build so i had to manually copy/change the shader in the build folder.

This was in Kdevelop so I'm not sure ifs a IDE specific issue, but as a quality of life i added:

```
add_custom_command(TARGET CGFX5 POST_BUILD        
    COMMAND ${CMAKE_COMMAND} -E copy_directory    
        "${PROJECT_SOURCE_DIR}/res"               
        "$<TARGET_FILE_DIR:CGFX5>/res")  
```

This requires Cmake to be minimum 3.3 to work

**Comment by Haeri** [comment]
JanWaltl fix worked for me too on Win 10 with VS 2017

**Comment by faltenberg** [comment]
The newest commit didn't change anything for me. Working on Manjaro (Archlinux) 64bit.

> OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

I will look into the code during weekend.

**Comment by BennyQBD** [comment]
Here's the status of this: I'm reasonably convinced that the real issue is attributes not getting bound to proper locations (hence JanWatl's fix). As some people mentioned, it would probably be better to use OpenGL methods to do this binding.

Here's where things get murky. (There's a TL;DR of how you can help at the end)

In the commit I made with the debuggerTemp flag, I silently changed part of the OpenGL backend as a test: I commented out the code binding attributes (the addAllAttributes method in openGLRenderDevice.cpp). Despite this change, it appears nothing was affected, and even more surprisingly, a shader which depended on proper attribute locations (the one drawing the white triangle) worked correctly.

I did some testing, and discovered something very odd: In a GLSL shader, if you use the "in" keyword instead of the "attribute" keyword, then using glGetProgramiv(program, GL_ACTIVE_ATTRIBUTES, &numActiveAttribs); will return 0 active attributes. This would be an easy fix (just use "attribute", not "in") except that the "attribute" keyword is officially removed from GLSL 140 and onwards. Even more strangely, since the layout solution is NOT officially supported until GLSL 330 and onwards, it would appear that in OpenGL 3.2, there is no way to correctly identify what needs to be bound in a shader short of writing a custom GLSL parser.

(TL;DR begins) Clearly, this seems like a ludicrous answer, so here's my question: Is there some way to identify the valid "in" variables for a vertex shader so they can be bound, similar to how it is done for attributes (so far, I've been unable to find such a technique)? And if not, is there anyone who still has drivers that support OpenGL 3.2 but NOT OpenGL 3.3?

**Comment by janwaltl** [comment]
You are calling `glGetProgramiv(program, GL_ACTIVE_ATTRIBUTES);` before linking the program, that does not seem right.
If I reverse the order, it shows 3 active attributes to me, but it lists them in reverse order(transformMat first) so it still assigns wrong locations. Maybe you could keep a list of names with predefined locations - position would always have 0, UVs 1... But as I said, you are using instanced arrays, they are OpenGL 3.3+

**Comment by BennyQBD** [comment]
@JanWaltl You are absolutely correct. It's amazing how after debugging for a while you can overlook the simplest things.

Edit: That's odd about the ordering however. I'll look into changing the vertex array system so it's order independent

**Comment by BennyQBD** [comment]
I implemented the solution of using layouts if they are available, and only running the attribute code if OpenGL is set old enough that they are unsupported. Theoretically, everything should be working now. Please let me know!

**Comment by faltenberg** [comment]
Yep, I see a bunch of triangles now. Moving very fast though, but I guess it updates them as fast as possible, so a feature.

**Comment by janwaltl** [comment]
Works for me on both Nvidia and Intel :] . But the code is not safe. Before you relied on that compiler set same locations as you in VAO. Now you rely on that OpenGL 3.2- will iterate through attributes in the same way as in VAO. Both is implementation-defined. On my Intel, the compiler iterates through them in order it assigned them their locations: (That also explains the bug earlier)
![image](https://user-images.githubusercontent.com/13469195/39379718-790d9f08-4a5c-11e8-80dd-b4bd14040b07.png). 
The order is different from your VAO so it won't work reliably(no idea why 0,4,5 were chosen). That order can change just by adding code to a shader. Now its only OpenGL 3.2- issue though and probably not worth solving looking at GL versions in this thread.
BTW [gpuinfo.org](gpuinfo) is great site to see what is supported on which GPUs.

**Comment by Thundzz** [comment]
Hey, I tested the code on the following platforms:
- Windows 10 (nvidia gpu)   👍  -> 👍 
- Windows 10 (intel gpu) 👎  -> 👍 
- Ubuntu (Virtualbox graphics adapter)  👎  -> 👍 

The issue seems resolved to me.

@faltenberg: The triangles moving very fast is the expected result  (example here https://www.youtube.com/watch?v=Mnxosx1XGw8), and the frames are capped to 60 FPS, so I don't understand what feature you would be talking about.

**Comment by faltenberg** [comment]
@Thundzz I mean that it's not a bug if the triangles are moving fast, but a feature.

**Comment by BennyQBD** [comment]
@JanWaltl You are correct that the old attribute selection won't always work, however, the code isn't using that anymore (or if it is, then I've done something wrong. The addAllAttribtues function should be returning immediately without doing anything because it detects OpenGL is version 3.2 or above). The code is using your original layout solution in the shader itself. I've left the method in so that if for some reason early OpenGL versions must be targeted, then there is some sort of base to work from.

I should clarify, right now the initialization forces OpenGL 3.2 core or above. If someone tries to run with an earlier OpenGL version right now, it should crash with an error rather than run the potentially faulty code.

**Comment by DamianReloaded** [comment]
Confirmed it works on ATI with the new changes when cloning the first time now.

**Comment by BennyQBD** [comment]
People are saying this is resolved, and I'm no longer getting any reports of this issue. Closed.
